openapi: 3.0.1
info:
  title: JokesBot
  description: JokesBot FastText model
  contact:
    email: konstantin.albul@gmail.com
  version: 0.0.1
servers:
- url: http://127.0.0.1:5000/
  description: Test server

paths:
  /answer:
    post:
      summary: Answer endpoint
      operationId: answer
      requestBody:
        description: Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/jokeThemeInput'
        required: true
      responses:
        default:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jokeOutput'

components:
  schemas:
    jokeThemeInput:
      type: object
      properties:
        question: 
          type: string
          description: Joke theme/keywords
      example:
        question: анекдот про чукчу

    jokeOutput:
      type: object
      properties:
        message: 
          type: object
          properties: 
            answer: 
              type: string
              description: Joke text
        status_code: 
          type: integer
          format: int32
          description: HTTP response code
      example:
        message:
          answer: Чукча интересуется у дальнобойщика:- Водителя, до тайги довезешь?- Нет.- А \"камаза\" довезет?
        status_code: 200

    OutputFalse:
      type: object
      properties:
        errors: 
          type: array
          items: 
            type: string
        status_code: 
          type: integer
          format: int32
          description: HTTP response code
      example:
        errors:
          - 'The request body is not JSON'
        status_code: 400
